/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import java.awt.Color;

/**
 *
 * @author salom
 */
public class Login extends javax.swing.JFrame {

    int xMouse,yMouse;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        PanExit = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        Barra = new javax.swing.JPanel();
        UESFMO = new javax.swing.JLabel();
        Tienda = new javax.swing.JLabel();
        favicon = new javax.swing.JLabel();
        iniciarSesion = new javax.swing.JLabel();
        USUARIO = new javax.swing.JLabel();
        cajaDeUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        contrasenia = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cajaDeContraseña = new javax.swing.JPasswordField();
        Signin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanExit.setBackground(new java.awt.Color(255, 255, 255));
        PanExit.setForeground(new java.awt.Color(0, 0, 0));
        PanExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanExit.setEnabled(false);

        exit.setForeground(new java.awt.Color(0, 0, 0));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PanExitLayout = new javax.swing.GroupLayout(PanExit);
        PanExit.setLayout(PanExitLayout);
        PanExitLayout.setHorizontalGroup(
            PanExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanExitLayout.createSequentialGroup()
                .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanExitLayout.setVerticalGroup(
            PanExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Background.add(PanExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        Barra.setBackground(new java.awt.Color(255, 255, 255));
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        Background.add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 30));

        UESFMO.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UESFMO.setForeground(new java.awt.Color(255, 255, 255));
        UESFMO.setText("UES FMO");
        Background.add(UESFMO, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 70, 20));

        Tienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/tienda.png"))); // NOI18N
        Tienda.setText("jLabel1");
        Tienda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TiendaMousePressed(evt);
            }
        });
        Background.add(Tienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 510, 500));

        favicon.setBackground(new java.awt.Color(0, 0, 0));
        favicon.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        favicon.setForeground(new java.awt.Color(0, 0, 0));
        favicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/favicon.png"))); // NOI18N
        favicon.setText("FMOcc");
        Background.add(favicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        iniciarSesion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        iniciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        iniciarSesion.setText("INICIAR SESIÓN");
        Background.add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        USUARIO.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        USUARIO.setForeground(new java.awt.Color(0, 0, 0));
        USUARIO.setText("USUARIO");
        Background.add(USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        cajaDeUsuario.setBackground(new java.awt.Color(255, 255, 255));
        cajaDeUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cajaDeUsuario.setForeground(new java.awt.Color(204, 204, 204));
        cajaDeUsuario.setText("Ingrese su nombre de usuario");
        cajaDeUsuario.setBorder(null);
        cajaDeUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaDeUsuarioMousePressed(evt);
            }
        });
        Background.add(cajaDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 310, -1));

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        Background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 320, 10));

        contrasenia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        contrasenia.setForeground(new java.awt.Color(0, 0, 0));
        contrasenia.setText("CONTRASEÑA");
        Background.add(contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 20));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        Background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 320, 10));

        cajaDeContraseña.setBackground(new java.awt.Color(255, 255, 255));
        cajaDeContraseña.setForeground(new java.awt.Color(204, 204, 204));
        cajaDeContraseña.setText("jPasswordField1");
        cajaDeContraseña.setBorder(null);
        cajaDeContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cajaDeContraseñaMousePressed(evt);
            }
        });
        Background.add(cajaDeContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 320, -1));

        Signin.setBackground(new java.awt.Color(0, 134, 190));
        Signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SigninMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SigninMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SigninMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTRAR");

        javax.swing.GroupLayout SigninLayout = new javax.swing.GroupLayout(Signin);
        Signin.setLayout(SigninLayout);
        SigninLayout.setHorizontalGroup(
            SigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SigninLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        SigninLayout.setVerticalGroup(
            SigninLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SigninLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        Background.add(Signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TiendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TiendaMousePressed
        
    }//GEN-LAST:event_TiendaMousePressed

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
      int x = evt.getXOnScreen();
      int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
       
    }//GEN-LAST:event_BarraMouseDragged

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        xMouse = evt.getX();
        yMouse =evt.getY();
    }//GEN-LAST:event_BarraMousePressed

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
    PanExit.setBackground(Color.red);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
      System.exit(0);  
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
       PanExit.setBackground(Color.WHITE);
    }//GEN-LAST:event_exitMouseExited

    private void SigninMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninMouseEntered
      Signin.setBackground(new Color(0,156,223));
    }//GEN-LAST:event_SigninMouseEntered

    private void SigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninMouseExited
        Signin.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_SigninMouseExited

    private void cajaDeUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaDeUsuarioMousePressed
       if(cajaDeUsuario.getText().equals("Ingrese su nombre de usuario")){
           
        cajaDeUsuario.setText("");
        cajaDeUsuario.setForeground(Color.BLACK);
       }
       if(String.valueOf(cajaDeContraseña.getPassword()).isEmpty()){
           
        cajaDeContraseña.setText("jPasswordField1");
        cajaDeContraseña.setForeground(Color.gray);
       }
     
    }//GEN-LAST:event_cajaDeUsuarioMousePressed

    private void cajaDeContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaDeContraseñaMousePressed
        if(String.valueOf(cajaDeContraseña.getPassword()).equals("jPasswordField1")){
        cajaDeContraseña.setText("");
        cajaDeContraseña.setForeground(Color.black);
            
        }
        if(cajaDeUsuario.getText().isEmpty()){
            
        cajaDeUsuario.setText("Ingrese su nombre de usuario");
        cajaDeUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_cajaDeContraseñaMousePressed

    private void SigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SigninMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this, "Datos del Usuario:\nUsuario: "+cajaDeUsuario.getText()+"\nContraseña: "+String.valueOf(cajaDeContraseña.getPassword()),"LOGIN",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_SigninMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Barra;
    private javax.swing.JPanel PanExit;
    private javax.swing.JPanel Signin;
    private javax.swing.JLabel Tienda;
    private javax.swing.JLabel UESFMO;
    private javax.swing.JLabel USUARIO;
    private javax.swing.JPasswordField cajaDeContraseña;
    private javax.swing.JTextField cajaDeUsuario;
    private javax.swing.JLabel contrasenia;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel favicon;
    private javax.swing.JLabel iniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
